services:
  database:
    image: eldoc92/postgres-rag-arm64:latest
    environment:
      - POSTGRES_USER=embediq
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=embediq
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U embediq']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - embediq-network

  backend:
    build:
      context: ./src
    environment:
      - DATABASE_URL=postgresql://embediq:devpassword@database:5432/embediq
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - DATA_DIR=/data/embediq/users
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - user_data:/data/embediq/users
    ports:
      - '8080:8000'
    networks:
      - embediq-network

networks:
  embediq-network:
    driver: bridge

volumes:
  postgres_data:
  user_data:
